# -*- coding: utf-8 -*-
"""kalkulator persegi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odfsZ6N8_omdCM9VJ54sf09HfF4JkTxj
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

def calculate_square_properties(sisi_value):
    """
    Menghitung keliling dan luas persegi berdasarkan panjang sisi.
    """
    keliling = 4 * sisi_value
    luas = sisi_value * sisi_value
    return keliling, luas

def on_sisi_change(change):
    """
    Fungsi yang dipanggil setiap kali nilai sisi berubah.
    """
    with output_area:
        clear_output(wait=True)
        sisi = change['new']
        if sisi > 0:
            keliling, luas = calculate_square_properties(sisi)
            print(f"Panjang Sisi: {sisi} cm")
            print(f"Keliling Persegi: {keliling} cm")
            print(f"Luas Persegi: {luas} cm^2")
        elif sisi == 0:
            print("Panjang sisi tidak boleh nol. Masukkan nilai positif.")
        else:
            print("Panjang sisi harus positif.")

# Membuat slider interaktif untuk panjang sisi
sisi_slider = widgets.FloatSlider(
    value=5.0,  # Nilai awal
    min=0.1,    # Nilai minimum
    max=20.0,   # Nilai maksimum
    step=0.1,   # Langkah perubahan
    description='Panjang Sisi (cm):',
    orientation='horizontal',
    readout=True,
    readout_format='.1f',
)

# Area output untuk menampilkan hasil
output_area = widgets.Output()

# Menghubungkan slider dengan fungsi on_sisi_change
sisi_slider.observe(on_sisi_change, names='value')

# Menampilkan slider dan area output
print("Selamat datang di Virtual Lab Persegi!")
print("Geser slider di bawah untuk mengubah panjang sisi persegi.")
display(sisi_slider, output_area)

# Inisialisasi tampilan awal
with output_area:
    keliling, luas = calculate_square_properties(sisi_slider.value)
    print(f"Panjang Sisi: {sisi_slider.value} cm")
    print(f"Keliling Persegi: {keliling} cm")
    print(f"Luas Persegi: {luas} cm^2")