# -*- coding: utf-8 -*-
"""kalkulator 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odfsZ6N8_omdCM9VJ54sf09HfF4JkTxj
"""

import streamlit as st

st.title("Kalkulator BMI (Indeks Massa Tubuh)")

nama = st.text_input("Masukkan nama Anda")
tinggi = st.number_input("Masukkan tinggi badan (cm)", min_value=100, max_value=250)
berat = st.number_input("Masukkan berat badan (kg)", min_value=30, max_value=200)

if st.button("Hitung BMI"):
    if tinggi > 0 and berat > 0:
        bmi = berat / ((tinggi / 100) ** 2)
        st.write(f"Halo, **{nama}** 👋")
        st.write(f"Nilai BMI Anda adalah **{bmi:.2f}**")

        if bmi < 18.5:
            st.warning("Berat badan Anda kurang.")
        elif 18.5 <= bmi < 25:
            st.success("Berat badan Anda normal.")
        elif 25 <= bmi < 30:
            st.info("Berat badan Anda berlebih.")
        else:
            st.error("Anda termasuk obesitas.")
    else:
        st.error("Tinggi dan berat badan harus lebih dari 0.")